CREATE TABLE StudentRegistration (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullName VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    otherNames VARCHAR(255),
    dob DATE NOT NULL,
    uceIndex VARCHAR(20) NOT NULL,
    totalAggregates INT NOT NULL,
    bestSubjects VARCHAR(255) NOT NULL,
    currentAddress VARCHAR(255) NOT NULL,
    mobileNumber VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    secondarySchool VARCHAR(255) NOT NULL,
    parentName VARCHAR(255) NOT NULL,
    parentTel VARCHAR(20) NOT NULL,
    courses VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    source VARCHAR(255) NOT NULL,
    otherSource VARCHAR(255),
    cvPath VARCHAR(255) NOT NULL,
    mentorLetterPath VARCHAR(255) NOT NULL,
    agreeTerms TINYINT(1) NOT NULL,
    submissionDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
